all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
all_joints_names:
- head
- tail
- paw1
- paw2
- paw3
- paw4
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_dawgsDec5/dawgs_Ayaan95shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: /Users/ayaanesmail/opt/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/mobilenet_v2_1.0_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_dawgsDec5/Documentation_data-dawgs_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: mobilenet_v2_1.0
num_joints: 6
pos_dist_thresh: 17
project_path: /Users/ayaanesmail/Desktop/DeepLabCut/conda-environments/dawgs-Ayaan-2019-12-05
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
